program SwimClubMeet;

uses
  Vcl.Forms,
  frmMain in 'frmMain.pas' {Main},
  Vcl.Themes,
  Vcl.Styles,
  dlgBootProgress in 'dlgBootProgress.pas' {BootProgress},
  dlgCloneSession in 'dlgCloneSession.pas' {CloneSession},
  dlgDivision in 'dlgDivision.pas' {Division},
  dlgHouse in 'dlgHouse.pas' {House},
  dlgLeaderBoard in 'dlgLeaderBoard.pas' {LeaderBoard},
  dlgNewSession in 'dlgNewSession.pas' {NewSession},
  dlgPointsScored in 'dlgPointsScored.pas' {PointsScored},
  dlgPreferences in 'dlgPreferences.pas' {Preferences},
  dmReports in 'dmReports.pas' {RPTS: TDataModule},
  dmSCM in 'dmSCM.pas' {SCM: TDataModule},
  dmSCMNom in 'dmSCMNom.pas' {SCMNom: TDataModule},
  dlgAutoBuild_Heats in 'dlgAutoBuild_Heats.pas' {AutoBuild_Heats},
  dlgQualifyTimes in 'dlgQualifyTimes.pas' {QualifyTimes},
  dlgSwapLanes in 'dlgSwapLanes.pas' {SwapLanes},
  dlgSwimmerCategory in 'dlgSwimmerCategory.pas' {SwimmerCategory},
  dlgDeleteMember in 'MEMBERS\dlgDeleteMember.pas' {DeleteMember},
  dlgFindMember in 'MEMBERS\dlgFindMember.pas' {FindMember},
  dlgGotoMember in 'MEMBERS\dlgGotoMember.pas' {GotoMember},
  dlgGotoMembership in 'MEMBERS\dlgGotoMembership.pas' {GotoMembership},
  frmManageMember in 'MEMBERS\frmManageMember.pas' {ManageMember},
  dlgDOBPicker in 'dlgDOBPicker.pas' {DOBPicker},
  dmManageMemberData in 'MEMBERS\dmManageMemberData.pas' {ManageMemberData: TDataModule},
  rptEventReportA in 'REPORTS\rptEventReportA.pas' {EventReportA: TDataModule},
  rptEventReportB in 'REPORTS\rptEventReportB.pas' {EventReportB: TDataModule},
  rptMarshallReportA in 'REPORTS\rptMarshallReportA.pas' {MarshallReportA: TDataModule},
  rptMarshallReportB in 'REPORTS\rptMarshallReportB.pas' {MarshallReportB: TDataModule},
  rptNominateReportA in 'REPORTS\rptNominateReportA.pas' {NominateReportA: TDataModule},
  rptNominateReportB in 'REPORTS\rptNominateReportB.pas' {NominateReportB: TDataModule},
  rptQTDistStrokeReportA in 'REPORTS\rptQTDistStrokeReportA.pas' {QTDistStrokeReportA: TDataModule},
  rptQTMemberReportA in 'REPORTS\rptQTMemberReportA.pas' {QTMemberReportA: TDataModule},
  rptQTSessionReportA in 'REPORTS\rptQTSessionReportA.pas' {QTSessionReportA: TDataModule},
  rptQTTableReportA in 'REPORTS\rptQTTableReportA.pas' {QTTableReportA: TDataModule},
  rptSessionReportA in 'REPORTS\rptSessionReportA.pas' {SessionReportA: TDataModule},
  rptSessionReportB in 'REPORTS\rptSessionReportB.pas' {SessionReportB: TDataModule},
  rptTimeKeeperReportA in 'REPORTS\rptTimeKeeperReportA.pas' {TimeKeeperReportA: TDataModule},
  rptTimeKeeperReportB in 'REPORTS\rptTimeKeeperReportB.pas' {TimeKeeperReportB: TDataModule},
  dlgAutoBuild_Finals in 'dlgAutoBuild_Finals.pas' {AutoBuild_Finals},
  dlgSelectPrinter in 'dlgSelectPrinter.pas' {SelectPrinter},
  dlgBatchProgress in 'dlgBatchProgress.pas' {BatchProgress},
  dlgAutoBuild_Batch in 'dlgAutoBuild_Batch.pas' {AutoBuildPref},
  dlgEntrantPicker in 'dlgEntrantPicker.pas' {EntrantPicker},
  dlgEntrantPickerCTRL in 'dlgEntrantPickerCTRL.pas' {EntrantPickerCTRL},
  rptMemberDetail in 'MEMBERS\rptMemberDetail.pas' {MemberDetail: TDataModule},
  rptMembersSummary in 'MEMBERS\rptMembersSummary.pas' {MembersSummary: TDataModule},
  rptMembersDetail in 'MEMBERS\rptMembersDetail.pas' {MembersDetail: TDataModule},
  rptMemberHistory in 'MEMBERS\rptMemberHistory.pas' {MemberHistory: TDataModule},
  rptMembersList in 'MEMBERS\rptMembersList.pas' {MembersList: TDataModule},
  rptHeatReportA in 'REPORTS\rptHeatReportA.pas' {HeatReportA: TDataModule},
  rptHeatReportB in 'REPORTS\rptHeatReportB.pas' {HeatReportB: TDataModule},
  SCMDefines in '..\SCM_SHARED\SCMDefines.pas',
  exeinfo in '..\SCM_SHARED\exeinfo.pas',
  SCMSimpleConnect in '..\SCM_SHARED\SCMSimpleConnect.pas',
  SCMUtility in '..\SCM_SHARED\SCMUtility.pas',
  dlgBasicLogin in '..\SCM_SHARED\dlgBasicLogin.pas' {BasicLogin},
  UEnvVars in '..\SCM_SHARED\UEnvVars.pas',
  Vcl.PlatformVclStylesActnCtrls in '..\SCM_SHARED\Vcl.PlatformVclStylesActnCtrls.pas',
  dlgAbout in '..\SCM_SHARED\dlgAbout.pas' {About},
  frmDisqualificationCodes in 'TOOLS\frmDisqualificationCodes.pas' {DisqualificationCodes},
  dlgAutoSchedule in 'TOOLS\dlgAutoSchedule.pas' {AutoSchedule},
  frame_TEAM in 'FRAME\frame_TEAM.pas' {frameTEAM: TFrame},
  frame_INDV in 'FRAME\frame_INDV.pas' {frameINDV: TFrame},
  dlgDCodePicker in 'dlgDCodePicker.pas' {DCodePicker},
  dlgTeamNameMenu in 'FRAME\dlgTeamNameMenu.pas' {TeamNameMenu},
  SCMHelpers in '..\SCM_SHARED\SCMHelpers.pas',
  dmSCMHelper in 'dmSCMHelper.pas',
  rptQTNotQualified in 'REPORTS\rptQTNotQualified.pas' {QTNotQualified: TDataModule},
  dlgMemberFilter in 'MEMBERS\dlgMemberFilter.pas' {MemberFilter},
  dlgTeamNamePicker in 'FRAME\dlgTeamNamePicker.pas' {TeamNamePicker},
  rptMarshallReportC in 'REPORTS\rptMarshallReportC.pas' {MarshallReportC: TDataModule},
  dlgSplitTimeTEAM in 'FRAME\dlgSplitTimeTEAM.pas' {SplitTimeTEAM},
  dlgSplitTimeINDV in 'FRAME\dlgSplitTimeINDV.pas' {SplitTimeINDV},
  rptMarshallReportA_ALT in 'REPORTS\rptMarshallReportA_ALT.pas' {MarshallReportA_ALT: TDataModule},
  rptMemberChart in 'MEMBERS\rptMemberChart.pas' {MemberChart: TDataModule},
  dlgSwimClubSwitch in 'dlgSwimClubSwitch.pas' {SwimClubSwitch},
  dlgSwimClubManage in 'dlgSwimClubManage.pas' {SwimClubManage},
  dlgMemberClub in 'MEMBERS\dlgMemberClub.pas' {MemberClub},
  rptMemberCheckData in 'MEMBERS\rptMemberCheckData.pas' {MemberCheckData: TDataModule},
  dmMemberHouse in 'MEMBERS\dmMemberHouse.pas' {MemberHouse: TDataModule},
  uABRelayExec in 'AUTOBUILD\uABRelayExec.pas',
  dmABRelayData in 'AUTOBUILD\dmABRelayData.pas' {ABRelayData: TDataModule},
  dlgABRelay in 'AUTOBUILD\dlgABRelay.pas' {ABRelay},
  dlgExportSessionJSON in 'EXPORT\dlgExportSessionJSON.pas' {ExportSessionJSON},
  XSuperJSON in '..\x-superobject\XSuperJSON.pas',
  XSuperObject in '..\x-superobject\XSuperObject.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Windows10 SlateGray');
  Application.CreateForm(TMain, Main);
  Application.Run;
end.
