program SwimClubMeet2;

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  Vcl.PlatformVclStylesActnCtrls in '..\SCM_SHARED\Vcl.PlatformVclStylesActnCtrls.pas',
  Advgrid in '..\VCL_TMS\Advgrid.pas',
  BaseGrid in '..\VCL_TMS\BaseGrid.pas',
  DBAdvGrid in '..\VCL_TMS\DBAdvGrid.pas',
  dmIMG in 'dmIMG.pas' {IMG: TDataModule},
  frmMain in 'frmMain.pas' {Main},
  dmSCM in 'dmSCM.pas' {SCM: TDataModule},
  dmCORE in 'dmCORE.pas' {CORE: TDataModule},
  dmSCMNom in 'dmSCMNom.pas' {SCMNom: TDataModule},
  SCMHelpers in '..\SCM_SHARED\SCMHelpers.pas',
  scmLogin in 'scmLogin.pas' {Login},
  scmSetting in 'scmSetting.pas',
  SCMUtility in '..\SCM_SHARED\SCMUtility.pas',
  uABRelayExec in 'AUTOBUILD\uABRelayExec.pas',
  uDefines in 'uDefines.pas',
  UEnvVars in '..\SCM_SHARED\UEnvVars.pas',
  uEvent in 'uEvent.pas',
  uHeat in 'uHeat.pas',
  uLane in 'uLane.pas',
  uSession in 'uSession.pas',
  uSwimClub in 'uSwimClub.pas',
  uTeam in 'uTeam.pas',
  XSuperJSON in '..\x-superobject\XSuperJSON.pas',
  XSuperObject in '..\x-superobject\XSuperObject.pas',
  dlgAbout in '..\SCM_SHARED\dlgAbout.pas' {About},
  dlgABRelay in 'AUTOBUILD\dlgABRelay.pas' {ABRelay},
  dlgAutoBuild_Batch in 'dlgAutoBuild_Batch.pas' {AutoBuildPref},
  dlgAutoBuild_Finals in 'dlgAutoBuild_Finals.pas' {AutoBuild_Finals},
  dlgAutoBuild_Heats in 'dlgAutoBuild_Heats.pas' {AutoBuild_Heats},
  dlgAutoSchedule in 'TOOLS\dlgAutoSchedule.pas' {AutoSchedule},
  dlgBatchProgress in 'dlgBatchProgress.pas' {BatchProgress},
  dlgBootProgress in 'dlgBootProgress.pas' {BootProgress},
  dlgCheckMemberRequisites in 'dlgCheckMemberRequisites.pas' {CheckMemberRequisites},
  dlgCloneSession in 'dlgCloneSession.pas' {CloneSession},
  dlgDatePicker in 'dlgDatePicker.pas' {DOBPicker},
  dlgDCodePicker in 'dlgDCodePicker.pas' {DCodePicker},
  dlgDeleteMember in 'MEMBERS\dlgDeleteMember.pas' {DeleteMember},
  dlgDivision in 'dlgDivision.pas' {Division},
  dlgEditSession in 'dlgEditSession.pas' {EditSession},
  dlgEntrantPicker in 'dlgEntrantPicker.pas' {EntrantPicker},
  dlgEntrantPickerCTRL in 'dlgEntrantPickerCTRL.pas' {EntrantPickerCTRL},
  dlgExportSessionJSON in 'EXPORT\dlgExportSessionJSON.pas' {ExportSessionJSON},
  dlgFindMember in 'MEMBERS\dlgFindMember.pas' {FindMember},
  dlgGotoMember in 'MEMBERS\dlgGotoMember.pas' {GotoMember},
  dlgGotoMembership in 'MEMBERS\dlgGotoMembership.pas' {GotoMembership},
  dlgHouse in 'dlgHouse.pas' {House},
  dlgLeaderBoard in 'LEADERBOARD\dlgLeaderBoard.pas' {LeaderBoard},
  dlgMemberClub in 'MEMBERS\dlgMemberClub.pas' {MemberClub},
  dlgMemberFilter in 'MEMBERS\dlgMemberFilter.pas' {MemberFilter},
  dlgNewSession in 'dlgNewSession.pas' {NewSession},
  dlgPointsScored in 'dlgPointsScored.pas' {PointsScored},
  dlgPreferences in 'dlgPreferences.pas' {Preferences},
  dlgQualifyTimes in 'dlgQualifyTimes.pas' {QualifyTimes},
  dlgSelectPrinter in 'dlgSelectPrinter.pas' {SelectPrinter},
  dlgSplitTimeINDV in 'FRAME\dlgSplitTimeINDV.pas' {SplitTimeINDV},
  dlgSplitTimeTEAM in 'FRAME\dlgSplitTimeTEAM.pas' {SplitTimeTEAM},
  dlgSwapLanes in 'dlgSwapLanes.pas' {SwapLanes},
  dlgSwimClubManage in 'dlgSwimClubManage.pas' {SwimClubManage},
  dlgSwimClubSwitch in 'dlgSwimClubSwitch.pas' {SwimClubSwitch},
  dlgSwimmerCategory in 'dlgSwimmerCategory.pas' {SwimmerCategory},
  dlgTeamNameMenu in 'FRAME\dlgTeamNameMenu.pas' {TeamNameMenu},
  dlgTeamNamePicker in 'FRAME\dlgTeamNamePicker.pas' {TeamNamePicker},
  dmABRelayData in 'AUTOBUILD\dmABRelayData.pas' {ABRelayData: TDataModule},
  dmAutoBuildV2 in 'dmAutoBuildV2.pas' {AutoBuildV2: TDataModule},
  dmLeaderBoardData in 'LEADERBOARD\dmLeaderBoardData.pas' {LeaderBoardData: TDataModule},
  dmManageMemberData in 'MEMBERS\dmManageMemberData.pas' {ManageMemberData: TDataModule},
  dmMemberHouse in 'MEMBERS\dmMemberHouse.pas' {MemberHouse: TDataModule},
  dmSCMHelper in 'dmSCMHelper.pas',
  exeinfo in '..\SCM_SHARED\exeinfo.pas',
  f_FrameEvent in 'f_FrameEvent.pas' {FrameEvent: TFrame},
  f_FrameHeat in 'f_FrameHeat.pas' {FrameHeat: TFrame},
  f_FrameLane in 'f_FrameLane.pas' {FrameLane: TFrame},
  f_FrameSession in 'f_FrameSession.pas' {FrameSession: TFrame},
  frame_INDV in 'FRAME\frame_INDV.pas' {frameINDV: TFrame},
  frame_TEAM in 'FRAME\frame_TEAM.pas' {frameTEAM: TFrame},
  frmDisqualificationCodes in 'TOOLS\frmDisqualificationCodes.pas' {DisqualificationCodes},
  frmManageMember in 'MEMBERS\frmManageMember.pas' {ManageMember},
  rptEventReportA in 'REPORTS\rptEventReportA.pas' {EventReportA: TDataModule},
  rptEventReportB in 'REPORTS\rptEventReportB.pas' {EventReportB: TDataModule},
  rptHeatReportA in 'REPORTS\rptHeatReportA.pas' {HeatReportA: TDataModule},
  rptHeatReportB in 'REPORTS\rptHeatReportB.pas' {HeatReportB: TDataModule},
  rptMarshallReportA in 'REPORTS\rptMarshallReportA.pas' {MarshallReportA: TDataModule},
  rptMarshallReportA_ALT in 'REPORTS\rptMarshallReportA_ALT.pas' {MarshallReportA_ALT: TDataModule},
  rptMarshallReportB in 'REPORTS\rptMarshallReportB.pas' {MarshallReportB: TDataModule},
  rptMarshallReportC in 'REPORTS\rptMarshallReportC.pas' {MarshallReportC: TDataModule},
  rptMemberChart in 'MEMBERS\rptMemberChart.pas' {MemberChart: TDataModule},
  rptMemberCheckData in 'MEMBERS\rptMemberCheckData.pas' {MemberCheckData: TDataModule},
  rptMemberDetail in 'MEMBERS\rptMemberDetail.pas' {MemberDetail: TDataModule},
  rptMemberHistory in 'MEMBERS\rptMemberHistory.pas' {MemberHistory: TDataModule},
  rptMembersDetail in 'MEMBERS\rptMembersDetail.pas' {MembersDetail: TDataModule},
  rptMembersList in 'MEMBERS\rptMembersList.pas' {MembersList: TDataModule},
  rptMembersSummary in 'MEMBERS\rptMembersSummary.pas' {MembersSummary: TDataModule},
  rptNominateReportA in 'REPORTS\rptNominateReportA.pas' {NominateReportA: TDataModule},
  rptNominateReportB in 'REPORTS\rptNominateReportB.pas' {NominateReportB: TDataModule},
  rptQTDistStrokeReportA in 'REPORTS\rptQTDistStrokeReportA.pas' {QTDistStrokeReportA: TDataModule},
  rptQTMemberReportA in 'REPORTS\rptQTMemberReportA.pas' {QTMemberReportA: TDataModule},
  rptQTNotQualified in 'REPORTS\rptQTNotQualified.pas' {QTNotQualified: TDataModule},
  rptQTSessionReportA in 'REPORTS\rptQTSessionReportA.pas' {QTSessionReportA: TDataModule},
  rptQTTableReportA in 'REPORTS\rptQTTableReportA.pas' {QTTableReportA: TDataModule},
  rptSessionReportA in 'REPORTS\rptSessionReportA.pas' {SessionReportA: TDataModule},
  rptSessionReportB in 'REPORTS\rptSessionReportB.pas' {SessionReportB: TDataModule},
  rptTimeKeeperReportA in 'REPORTS\rptTimeKeeperReportA.pas' {TimeKeeperReportA: TDataModule},
  rptTimeKeeperReportB in 'REPORTS\rptTimeKeeperReportB.pas' {TimeKeeperReportB: TDataModule},
  f_FrameMember in 'f_FrameMember.pas' {FrameMember: TFrame};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Windows10 SlateGray');
  Application.CreateForm(TIMG, IMG);
  Application.CreateForm(TMain, Main);
  Application.Run;
end.
